// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	OidcIssuers     string
	ServiceAccounts string
	Tenants         string
	Tokens          string
	Users           string
}{
	OidcIssuers:     "oidc_issuers",
	ServiceAccounts: "service_accounts",
	Tenants:         "tenants",
	Tokens:          "tokens",
	Users:           "users",
}
